Script Project uses Saltarelle compiler (from  Nugit, see commands below) to make it compile C# code to javascript.

Script Project has a post build event which copies the compiled javascript file to the desired directory. 
copy "$(TargetDir)$(TargetName).js" "$(SolutionDir)\CordovaExample\www\js\

This starter app is for using phonegap with saltarelle.


There are two projects in this solution.  ScriptProject is a c# console application which compiles into javascript.  I first created it as a console app, but now it compiles to Javascript, thanks to the Saltarelle compiler project. The compiled javascript is compied to the web project using a post build command in ScriptProject.
 
* Nugit Commands to make ScriptProject compile to javascript:
- Install-Package Saltarelle.Compile
- Install-Package Saltarelle.Web
- Install-Package Saltarelle.Linq
- Install-Package Quicklight.Mobile


* BlackBerry Code Signing
- obtain code key from black berry site
- install webworks sdk from [[https://developer.blackberry.com/html5/download/#smartphones][here]]
- generate signing keys following [[https://developer.blackberry.com/html5/documentation/signing_setup_smartphone_apps_1920010_11.html][these instructions]] 